[package]
name = "glossarium"
version = "0.1.1"
entrypoint = "glossary.typ"
authors = ["slashformotion", "Dherse"]
license = "MIT"
description = "Glossarium is a simple, easily customizable typst glossary."
repository = "https://github.com/slashformotion/glossarium"
exclude = ["LICENCE", "example/*"]